Week7LabPin/Controllers/InterestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Week7LabPin.Migrations;
using Week7LabPin.Models;

namespace Week7LabPin.Controllers
{
    [Authorize]
    public class InterestsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Interests
        public ActionResult Index()
        {
            return View(db.Interests.ToList());
        }

        public ActionResult GetImage(int Id)
        {
            var pin = db.Interests.Find(Id);
            return File(pin.Image, "image");
        }

        public ActionResult List()
        {
            var list = db.Interests.ToList().Select(p => new { p.URL, p.Link, p.Comment }).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult New(string ImageUrl, string Link, string Comment)
        {
            var currentUser = db.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();
            var physicalByteImage = Configuration.GetImageByteArray(ImageUrl);
            var newinterest = new Interest() { URL = Link, Comment = Comment, Poster = currentUser, Image = physicalByteImage };
            db.Interests.Add(newinterest);
            db.SaveChanges();
            

            return Json(new { Link = newinterest.Link });
        }
    }
}

Week7LabPin/Views/Interests/Index.cshtml
@model IEnumerable<Week7LabPin.Models.Interest>

@{
    ViewBag.Title = "Index";
}

<div class="container" ng-controller="interestCtrl">
    <div ng-repeat="interest in interests" class="col-md-4 col-sm-6 text-center" ng-class="{'clearfix' : $index % 3 == 0}">
        <img ng-src="{{interest.Link}}" /><br />
        <a ng-href="{{interest.URL}}">View Here</a>
        <p>{{interest.Comment}}</p>


    </div>


    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg col-sm-2" data-toggle="modal" data-target="#myModal">
        Add Pin
    </button>


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Pin</h4>

                </div>
                <form ng-submit="addPin(newInterest)">
                    <div class="modal-body">

                        <div class="container-fluid">

                            <div class="form-horizontal">
                                <div class="form-group">
                                    <label class="control-label col-md-2" for="ImageUrl">Image URL</label>
                                    <div class="col-md-10">
                                        <input type="text" ng-model="newInterest.Link" class="form-control" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2" for="Link">Link</label>
                                    <div class="col-md-10">
                                        <input type="text" ng-model="newInterest.URL" class="form-control" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2" for="Comment">Comment</label>
                                    <div class="col-md-10">
                                        <input type="text" ng-model="newInterest.Comment" class="form-control" />
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Pin It</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        (function () {
            var app = angular.module('interests', []);

            app.controller('interestCtrl', function ($scope, $http) {
                $scope.interests = [];
                $http.get('@Url.Action("List", "Interests")').success(function (data) {
                    $scope.interests = data;
                });

                $scope.addPin = function (newInterest) {
                    console.log(newInterest);
                    $http.post('/Interests/New/', { ImageUrl: newInterest.Link, Link: newInterest.URL, Comment: newInterest.Comments })
                        .then(function (response) {
                            console.log(response);
                            newInterest.Link = response.data.Link;

                            $scope.interests.push(newInterest);

                            $scope.newInterest = {};

                            $('#myModal').modal('hide');
                           
                        });
                };
            });
        })();

    </script>
}

Week7LabPin/Views/Interests/IndexDELETE.cshtml
@model Week7LabPin.Models.Interest

@{
    ViewBag.Title = "IndexDELETE";
}

<h2>IndexDELETE</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Interest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}